import type { Config } from 'jest'
import { pathsToModuleNameMapper } from 'ts-jest'

// Paths mapeados para resolver @soe/* em testes e em source files importados
const paths = {
  '@soe/core-config': ['./packages/core/config/src/index.ts'],
  '@soe/core-logger': ['./packages/core/logger/src/index.ts'],
  '@soe/core-errors': ['./packages/core/errors/src/index.ts'],
  '@soe/core-time': ['./packages/core/time/src/index.ts'],
  '@soe/core-identity': ['./packages/core/identity/src/index.ts'],
  '@soe/core-validation': ['./packages/core/validation/src/index.ts'],
  '@soe/core-events': ['./packages/core/events/src/index.ts'],
  '@soe/core-audit': ['./packages/core/audit/src/index.ts'],
  '@soe/core-health': ['./packages/core/health/src/index.ts'],
  '@soe/core-observability': ['./packages/core/observability/src/index.ts'],
  '@soe/cap-01': ['./packages/cap-01/src/index.ts'],
  '@soe/cap-02': ['./packages/cap-02/src/index.ts'],
  '@soe/cap-03': ['./packages/cap-03/src/index.ts'],
  '@soe/cap-04': ['./packages/cap-04/src/index.ts'],
  '@soe/cap-04/*': ['./packages/cap-04/src/*'],
  '@soe/cap-02/*': ['./packages/cap-02/src/*'],
  '@soe/cap-03/*': ['./packages/cap-03/src/*'],
  '@soe/cap-05': ['./packages/cap-05/src/index.ts'],
  '@soe/cap-05/*': ['./packages/cap-05/src/*'],
  '@soe/cap-06': ['./packages/cap-06/src/index.ts'],
  '@soe/cap-06/*': ['./packages/cap-06/src/*'],
  '@soe/cap-07': ['./packages/cap-07/src/index.ts'],
  '@soe/cap-07/*': ['./packages/cap-07/src/*'],
  '@soe/cap-08': ['./packages/cap-08/src/index.ts'],
  '@soe/cap-08/*': ['./packages/cap-08/src/*'],
  '@soe/cap-09': ['./packages/cap-09/src/index.ts'],
  '@soe/cap-09/*': ['./packages/cap-09/src/*'],
  '@soe/implantacao': ['./packages/implantacao/src/index.ts'],
  '@soe/implantacao/*': ['./packages/implantacao/src/*'],
  '@soe/dashboards': ['./packages/dashboards/src/index.ts'],
  '@soe/dashboards/*': ['./packages/dashboards/src/*'],
  '@soe/administracao': ['./packages/administracao/src/index.ts'],
  '@soe/administracao/*': ['./packages/administracao/src/*'],
  '@soe/configuracao': ['./packages/configuracao/src/index.ts'],
  '@soe/configuracao/*': ['./packages/configuracao/src/*'],
}

const config: Config = {
  testEnvironment: 'node',
  rootDir: '.',
  testMatch: [
    '<rootDir>/packages/core/*/tests/**/*.test.ts',
    '<rootDir>/packages/cap-01/tests/**/*.test.ts',
    '<rootDir>/packages/cap-02/tests/**/*.test.ts',
    '<rootDir>/packages/cap-03/tests/**/*.test.ts',
    '<rootDir>/packages/cap-04/tests/**/*.test.ts',
    '<rootDir>/packages/cap-05/tests/**/*.test.ts',
    '<rootDir>/packages/cap-06/tests/**/*.test.ts',
    '<rootDir>/packages/cap-07/src/tests/**/*.test.ts',
    '<rootDir>/packages/cap-08/src/tests/**/*.test.ts',
    '<rootDir>/packages/cap-09/src/tests/**/*.test.ts',
    '<rootDir>/packages/implantacao/src/tests/**/*.test.ts',
    '<rootDir>/packages/dashboards/src/tests/**/*.test.ts',
    '<rootDir>/packages/administracao/src/tests/**/*.test.ts',
    '<rootDir>/packages/configuracao/src/tests/**/*.test.ts',
    '<rootDir>/tests/business-flows/**/*.test.ts',
  ],
  moduleNameMapper: pathsToModuleNameMapper(paths, { prefix: '<rootDir>/' }),
  collectCoverageFrom: [
    'packages/core/*/src/**/*.ts',
    '!packages/core/*/src/index.ts',
    'packages/cap-01/src/**/*.ts',
    '!packages/cap-01/src/index.ts',
    'packages/cap-02/src/**/*.ts',
    '!packages/cap-02/src/index.ts',
    'packages/cap-03/src/**/*.ts',
    '!packages/cap-03/src/index.ts',
    'packages/cap-04/src/**/*.ts',
    '!packages/cap-04/src/index.ts',
    'packages/cap-05/src/**/*.ts',
    '!packages/cap-05/src/index.ts',
    'packages/cap-06/src/**/*.ts',
    '!packages/cap-06/src/index.ts',
    'packages/cap-07/src/**/*.ts',
    '!packages/cap-07/src/index.ts',
    'packages/cap-08/src/**/*.ts',
    '!packages/cap-08/src/index.ts',
    'packages/cap-09/src/**/*.ts',
    '!packages/cap-09/src/index.ts',
    'packages/implantacao/src/**/*.ts',
    '!packages/implantacao/src/index.ts',
    'packages/dashboards/src/**/*.ts',
    '!packages/dashboards/src/index.ts',
    'packages/administracao/src/**/*.ts',
    '!packages/administracao/src/index.ts',
    'packages/configuracao/src/**/*.ts',
    '!packages/configuracao/src/index.ts',
  ],
  coverageThreshold: {
    global: { branches: 80, functions: 80, lines: 80, statements: 80 },
  },
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { tsconfig: './tsconfig.test.json' }],
  },
}

export default config
